<?php
$options = [
    'crypto' => [
        'USDT',
        'USDC',
        'BUSD',
        'TUSD',
        'DAI',
        'ALL-USD',
        'BTC',
        'BNB',
        'ETH'
    ],
    'fiat' => [
        'USD',
        'EUR',
        'CNY',
        'GBP',
        'KZT',
        'RUB',
        'TRY',
        'UAH'
    ],
    'exchange' => [
        'Купить' => 'BUY',
        'Продать' => 'SELL'
    ],
    'payment' => [
        'all-methods',
        'Advcash',
        'ALIPAY',
        'AltynBank',
        'ApplePay',
        'BANK',
        'Cashapp',
        'CashDeposit',
        'CashInPerson',
        'EurasianBank',
        'ForteBank',
        'GoMoney',
        'GoPay',
        'GPay',
        'HalykBank',
        'HomeCreditKazakhstan',
        'JysanBank',
        'Kapitalbank',
        'KaspiBank',
        'KoronaPay',
        'Monobank',
        'OTPBankRussia',
        'Payall',
        'Payeer',
        'Payme',
        'Paysend',
        'Paysera',
        'Paytm',
        'PerfectMoney',
        'PiPay',
        'PipolPay',
        'PrivatBank',
        'QIWI',
        'RaiffeisenBankRussia',
        'Revolut',
        'RosBank',
        'RUBfiatbalance',
        'SEPA',
        'SWIFT',
        'Tinkoff',
        'UAHfiatbalance',
        'Ukrsibbank',
        'UNIBANK',
        'UniCreditBulbank',
        'UniCreditRussia',
        'Vodafonecash',
        'WECHAT',
        'WesternUnion',
        'Wise'
    ]
];

$paylist = [
        'Все методы' => ['binance' => 'all-methods','okx' => 'all-methods','huobi' => 'all-methods','bybit' => 'all-methods'],
        'Advcash' => ['binance' => 'Advcash','okx' => '','huobi' => '','bybit' => ''],
        'ALIPAY' => ['binance' => 'ALIPAY','okx' => '','huobi' => '','bybit' => ''],
        'AltynBank' => ['binance' => 'AltynBank','okx' => '','huobi' => '','bybit' => ''],
        'ApplePay' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'BANK' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'Cashapp' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'CashDeposit' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'CashInPerson' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'EurasianBank' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'ForteBank' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'GoMoney' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'GoPay' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'GPay' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'HalykBank' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'HomeCreditKazakhstan' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'JysanBank' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'Kapitalbank' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'KaspiBank' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'KoronaPay' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'Monobank' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'OTPBankRussia' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'Payall' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'Pyypl' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'Payeer' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'Payme' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'Paysend' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'Paysera' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'Paytm' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'PerfectMoney' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'PiPay' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'PipolPay' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'PrivatBank' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'QIWI' => ['binance' => 'QIWI','okx' => '','huobi' => '','bybit' => ''],
        'RaiffeisenBankRussia' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'Revolut' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'RosBank' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        //'RUBfiatbalance' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'SEPA' => ['binance' => 'SEPA','okx' => '','huobi' => '','bybit' => ''],
        'SWIFT' => ['binance' => 'SWIFT','okx' => '','huobi' => '','bybit' => ''],
        'Tinkoff' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        //'UAHfiatbalance' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'Ukrsibbank' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'UNIBANK' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'UniCreditBulbank' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'UniCreditRussia' => ['binance' => '','okx' => '','huobi' => '','bybit' => ''],
        'WECHAT' => ['binance' => 'WECHAT','okx' => '','huobi' => '','bybit' => ''],
        'WesternUnion' => ['binance' => 'WesternUnion','okx' => '','huobi' => '','bybit' => ''],
        'Wise'  => ['binance' => 'Wise','okx' => '','huobi' => '','bybit' => '']
];
